# Generated by Django 4.2.24 on 2025-09-20 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(default='Indisponível', max_length=200)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('barber', 'date')},
            },
        ),
    ]
